### ISSUE TITLE
challenge1: fixing the levitation

### ISSUE THREAD

**Issue by stormsidali2001** [stormsidali2001/three-js-fiber-playground#2]
when we jump over a cube and stand on it  and try to create another cube at the bottom the player get pushed away into the sky

**Comment by aghiles-medane** [comment]
after installing all  the dependencies and runing the game i can see what bug you're talking about  , can you assign me this issue i'd like to give it a try .

**Comment by stormsidali2001** [comment]
Okay go ahead aghiles.

**Comment by stormsidali2001** [comment]
@aghiles-medane  i've recieved your pull request  then i've merged your updates into the main branch
